# SearchRuler
# Ref: https://helm.sh/docs/topics/charts/#the-chartyaml-file
apiVersion: v2
name: searchruler
type: application
description: >-
  A Helm chart for SearchRuler, a ruler Engine that allows you 
  to create and manage rules for your search engine.
version: 0.4.2 # chart version
appVersion: "0.4.1" # searchruler version
kubeVersion: ">=1.22.0-0" # kubernetes version
home: https://github.com/prosimcorp/searchruler
sources:
  - https://github.com/prosimcorp/searchruler
keywords:
  - freepik
  - prosimcorp
  - searchruler
  - gitops
maintainers:
  - name: Daniel Fradejas
    email: fradejasdaniel@gmail.com
    url: https://github.com/prosimcorp/searchruler
  - name: Alby Hern√°ndez
    email: donfumero@gmail.com
    url: https://github.com/prosimcorp/searchruler
  - name: prosimcorp
    url: https://github.com/prosimcorp
