# Reforma
# Ref: https://helm.sh/docs/topics/charts/#the-chartyaml-file
apiVersion: v2
name: reforma
type: application
description: A Helm chart for reforma, a Kubernetes operator to patch resources with information from other resources
version: 0.1.0 # chart version
appVersion: "0.3.0" # reforma version
kubeVersion: ">=1.22.0-0" # kubernetes version
home: https://github.com/prosimcorp/helm-charts
sources:
  - https://github.com/prosimcorp/helm-charts/tree/main/charts/reforma
  - https://github.com/prosimcorp/reforma
keywords:
  - prosimcorp
  - reforma
  - gitops
maintainers:
  - name: prosimcorp
    url: https://github.com/prosimcorp
